### ISSUE TITLE
thps2-tools has similar tools

### ISSUE THREAD

**Issue by JayFoxRox** [krystalgamer/spidey-tools#2]
I made my own tools which might be helpful, see https://github.com/JayFoxRox/thps2-tools

I do not remember wether I tested this my tools with Spiderman files. However, I used spidey-tools using prototyping (and then ditched it); [see my Patreon post for more information](https://www.patreon.com/posts/happy-birthday-30335553). So I assume that a lot of it still works.

**Comment by krystalgamer** [comment]
"Initially I made a script disassembler based on spidey-tools (as Neversoft's Spiderman game uses the same engine), but I quickly decided to drop that idea due to the poor quality of existing code."

oof


thanks for sharing, having more information and more people is always nice :)

**Comment by JayFoxRox** [comment]
>> I quickly decided to drop that idea due to the poor quality of existing code.
> 
> oof

I should elaborate on this for fairness:

- There's 3 tools, which all seem to do similar things:
    - trg (C): Basically only checks file header (why keep this?).
    - trg_disasm (Python): A working decoder split into 2 files, with binary strings (`b'\x8C\x00' : SetRestart,`) and confusing variable names (like `v249` or `v152` - probably IDA output?).
    - trg_disassembler (Python): A refactor of trg_disasm (why keep that?), however, I needed to be able to access one node from another node.
    The code was also too non-descriptive (read using `self.dereference(self.file_pointer, self.word)` etc.) for me. So it was hard to see what's going on.
    The most critical issue was that the output would not reflect the input file structure and it would not re-assemble. It seemed like a node "filter" with `get_restart_points` and `run_autoexec` (= only look at a few nodes, skipping the rest) - but I wanted to walk over all nodes in order (regardless of type), and emit as much info as possible per node. I wanted the output to look uniform and contain *all* bytes from the input. Code emitted by my tool doesn't reassemble (yet) either, but it's much closer to what's actually stored in the file (just turned into human-readable encoding). I believe this is crucial so readers can even begin to understand the structure of the file.
- Additionally, there's trg_dumper (Python) which requires IDA and isn't clear about what it does. Fortunately, THPS came with SYMBOLS.TDF which documents the commands + nodes anyway. So I didn't need this.
- The non-trg tools weren't interesting to me. Alternatives exist and I also wanted all my tools to be Python code for simplicity + possible Blender plugin.

**Comment by krystalgamer** [comment]
The repository contains historical progress of the reversal process that's why there's so many iterations of similar projects.

trg_dumper dumps the opcode and the symbol associated with it, it uses IDA since it generates the pseudo-code in such a manner:

```
case XX:
nullsub_1("SetFogColor %08X")
```

> The non-trg tools weren't interesting to me. Alternatives exist 
There are no alternatives for the other tools, with the exception of the pkr_extractor.

**Comment by JayFoxRox** [comment]
I feel your edit misrepresents my work (almost a year after the original post):
- It was never my intention to "plug my own shit" (if it was, then I wouldn't take part in discussions here). I also wouldn't use such language in any of my issues; it's unprofessional. I don't think such edits (changing someones wording) are acceptable at all.
- The removal of the blog-post link removes context. I'm fine with removing the link; although I don't see why it would be an issue. It should have been communicated that such links are not allowed (aren't they?).

I don't care for the link; but I do ask for the title to be changed back to something more sensical and professional. I don't want people to come across posts like this, thinking I wrote something like that.

If the link is removed, necessary context from my blog post should be preserved for the sake of the discussion (as your statement now doesn't contain any hints as to where it's quoting from, and all context is lost).

>> The non-trg tools weren't interesting to me. Alternatives exist [and I also wanted all my tools to be Python code]
>
> There are no alternatives for the other tools, with the exception of the pkr_extractor.

There is also tooling for PSX files in https://gist.github.com/iamgreaser/2a67f7473d9c48a70946018b73fa1e40 and https://github.com/denetii/io_thps_scene (both of which are linked from my post; the link you chose to remove).
As I said in my blog post: I didn't know about `io_thps_scene` PSX support until very late into my work. So my contribution was to port the logic from the iamgreaser script to Python (not realizing something comparable existed already).

**Comment by krystalgamer** [comment]
> (almost a year after the original post)

My original response was done after a quick glance at your issue, I completely forgot about it until a friend reminded me about it.

I've reviewed your issue yesterday and came to the conclusion it's garbage.


First of all:

* Issues are for **ISSUES**, your post was only showcasing your work. There's several ways to contact me, use them.

* The title was "thps2-tools contains similar tools", they're not similar in any way shape or form.

* Your tools are not helpful, they're THPS2 specific.

* You didn't test with Spider-Man files, so there's no point of claiming they're similar tools.

* Your post did not add any extra information to the issue. The only time my project is mentioned is in this line

>Initially I made a script disassembler based on spidey-tools (as Neversoft's Spiderman game uses the same engine), but I quickly decided to drop that idea due to the poor quality of existing code.

Besides my "oof" to your remark, it does not contribute anything to the """discussion"""

The article does not contain any meaningful information, I'll summarize:

1. I like game
2. I've contributed to emulation problems regarding game
3. More personal junk
4. Mentioning of other unrelated projects


5. I found gist, here's pic
6. I made tools, initally based on spidey-tools
7. system works with nodes
8. made psx converter

9. There's bugs which always existed
10. there's already a project for my work, lol


No technical details, nothing. Lack luster to the max.

> I also wouldn't use such language in any of my issues; it's unprofessional

Unprofessional it what terms? It's my repository, my rules. If you don't like the language get a corporate job.


> (crying over link) x3
If the link is removed, necessary context from my blog post should be preserved for the sake of the discussion

There's no discussion here, just you plugging your shit.

> There is also tooling for PSX files

If you actually spend some time looking at my work you'd know that even though the extension is PSX the content/format is vastly different. Greaser's works only with PS1 and io_thps_scene has wonky results. Also they have different goals.


> So if this article feels a bit rushed: that's why.

Rushed, lack luster and braggadocious article the trifecta of mediocrity. You could've picked the existing tools and written an article about the tools or the reversal process. But no, build the whole article with "i did this, that and this" to finish like this "it's abandoned lol, because they're redundant". I refuse to promote lazy work like that, it's far more unprofessional than some profanity.

The cherry on top of the cake is how you abandoned your project. You still have 3 open issues by yourself that were created 1 week before **this** issue.

**Comment by JayFoxRox** [comment]
> * Issues are for **ISSUES**, your post was only showcasing your work.

"Issue" does not just mean "Bug".

I found your tools useful for bootstrapping and I thought the audience for your tools might also appreciate similar tools.

Your tools, by that point had been rarely updated, not been documented, and there have been different variants of the same tools. Things like the PSX extractor are also incomplete.
So for anyone dealing with spidey-tools, it might also be interesting to look at other existing tools (mentioned in my blog post and my repository).

> There's several ways to contact me, use them.

This is an open-source project, and I have a project with a similar purpose, and an article providing an overview about projects in that domain (the underlying engine / tech). I wanted to reach out to the community that uses tools like yours or mine, not just you personally. So I don't see why I should have contacted you.

I could have created more issues on this repository, but I haven't used these tools for their intended purpose (whatever that is), so I don't feel comfortable doing that.

> * The title was "thps2-tools contains similar tools", they're not similar in any way shape or form.

They are *very* similar. They share many of the file-formats with a few variations.
Also much of the engine has been re-used and the games were developed by the same person: Mick West.

> * Your tools are not helpful, they're THPS2 specific.

They are mainly designed for THPS2, but have been shown to work with other games in the THPS series; and even unrelated games on the Neversoft Big Guns engine.

I also used spidey-tools for bootstrapping because those games are so similar.

> * You didn't test with Spider-Man files, so there's no point of claiming they're similar tools.

I don't *remember* if I did. I tested a bunch of games.
Also see the README or some of the source-code (because my tools do differentiate different versions of the engine).

> * Your post did not add any extra information to the issue.

It does add context about wanting something working quickly, ideally in Python etc.

It also shows that my tools aren't planned to be a long-term project. I was mostly curious how the game worked and was interested in finding unused content - my tools can do that so I consider them "complete" in that regard.

> The article does not contain any meaningful information, I'll summarize:
> [...]
> No technical details, nothing. Lack luster to the max.

My blog isn't meant to be technical.

The technical details can be found in the implementation (on GitHub).
My contact-details are also listed on the blog, in case anyone doesn't use GitHub. I'm always willing to talk about tech - just not on my blog.

> > I also wouldn't use such language in any of my issues; it's unprofessional
> 
> Unprofessional it what terms? It's my repository, my rules.

Your repository still has to follow the community guidelines of GitHub.. and social norms.
It's rude to edit a discussion the way you did (putting words in my mouth).

It also drags other people (who might use their personal account for business) into your non-PC way of handling things.

> There's no discussion here, just you plugging your shit.

I have mentioned a couple of things where context was provided in the blog post.

I also don't gain anything from linking my repository or blog post here.
This repository isn't exactly high-traffic, and my post isn't (as you also noticed) very polished either.
It can still be informative to some readers.

> > There is also tooling for PSX files
> 
> If you actually spend some time looking at my work [...]

I did only skim over your work (other than the TRG code, which I actually used).
I actually believe I found your work because of the comment on the PSX gist, so it was reasonable to assume the PSX format is similar.

> [...] you'd know that even though the extension is PSX the content/format is vastly different.

I doubt this, given the similarity of the PSX files in the games that I did look at. But I also haven't looked into Spiderman files in particular (and am not motivated to do so).
The TRG format is definitely largely the same.

> Greaser's works only with PS1 and io_thps_scene has wonky results.

I did adapt the gist for other platforms and made it work with Xbox files (and I believe also PC files?). The changes for that were minimal.
I'm also aware that io_thps_scene has some issues.

But at least those other projects do import the mesh and document some of the underlying concepts - your tools don't.
I think referencing those other tools helps with understanding the formats. This is also why I link to spidey-tools from thps2-tools, even though it's not 100% binary compatible (or THPS related).

> Also they have different goals.

I'm not even sure what the goal of spidey-tools is; it doesn't seem to be documented as part of this repository.

> > So if this article feels a bit rushed: that's why.
> 
> Rushed, lack luster and braggadocious article the trifecta of mediocrity.

It was indeed rushed; but the blog isn't a priority for me: My code contributions are.
I don't think it was "braggadocious" either; it's just not very objective or technical: My code contributions are.

Wether it's lackluster is subjective. I'm a coder, not a writer (and also not a native speaker).

> You could've picked the existing tools and written an article about the tools or the reversal process.

The existing tools didn't do what I wanted to do. I also did not care for writing technical documentation.
It's my hobby, and I get to decide what I do with my free time.

My blog is also mostly read by developers who are looking to find new topics (they typically care about an overview), or users of emulators, who might care about games, but not necessarily the underlying details. If they care about the tech, they can read the source-code of the linked projects.

>  But no, build the whole article with "i did this, that and this" [...]

It's my personal blog - of course I'll report what *I* do or did. Because that's what *I* get asked by people (particularly people who donate to me).

> [...] to finish like this "it's abandoned lol, because they're redundant".

I didn't say it was permanently abandoned. I said I *abandoned it in August* (implied: to be resurrected in September) and then sort-of forgot about it.
If anyone sends a PR to any of my projects I'll still look at it (as with most of my projects). Otherwise I'd have archived the repository.

The tools being redundant is unfortunate, but it wouldn't be a reason for abandoning them. Had I known about these tools, I'd probably have fixed existing code instead. Backporting or upstreaming now is a non-goal for me right now (busy with other projects and just not interested anymore).

> I refuse to promote lazy work like that, it's far more unprofessional than some profanity.

I don't think I'm being lazy. I have a track record of contributions and my own projects which did yield practical results.
In this instance, I did contribute some new knowledge and tooling (for the underlying formats, and also the games themselves). I just didn't write a technical article about it (and why should I?).

> The cherry on top of the cake is how you abandoned your project. You still have 3 open issues by yourself that were created 1 week before **this** issue.

It's not permanently abandoned; but *I* also don't plan to write any new code for it anytime soon.

The issues document things that *could* be added, but not actual bugs (one warns about a non-goal for example). I think this is also obvious from those issues. If someone else wanted to pick the project up, some of these tasks might be interesting.

The code itself is also helpful on its own, for people dealing with these kind of files, even if there isn't any progress on it (archived / unmaintained or otherwise).

Also, by that logic, this repository had also been abandoned: [it had also been inactive for about a year at some point](https://github.com/krystalgamer/spidey-tools/graphs/code-frequency). A lack of activity does not mean that a project is permanently abandoned.

**Comment by krystalgamer** [comment]
> I haven't used these tools for their intended purpose (whatever that is), so I don't feel comfortable doing that.

This summarizes the thread. My tools were developed for Spider-Man PC, so that custom textures could be injected to character models, nothing else. It doesn't export to blender of any of crap because it was **NOT DEVELOPED** for those purposes.


I'm not replying to every little piece of the word salad you just posted, not feeding into dumb pedantic behaviour.

Just to put this into perspective, you've come to the person that has reversed and documented some of the formats to showcase your tools and blog post, communicated via the incorrect channel, issues are for issues, they're not email threads. The tools were glued from existing works and the blog post a extremely surface level general overview (all of this done over the period of a week), the supreme unsalted cracker.

My work is **DOCUMENTED** on my blog and youtube channel, the former being the most technical one. Also bitching about ""undocumented"" work and then claiming that technical details can be found on the code is non-sensical.

The textures on the level PSX can already be exported with pstex developed by DCxDemo, by the way justifying the lack of a feature with lack of incentive is arrogant and quite honest un-welcomed.

Locking this shit up, i'm done with your egotrip.
